// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgzrqjtgzxnddvapakmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnenJxanRnenhuZGR2YXBha21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTgyNjEsImV4cCI6MjA3MzI3NDI2MX0.hPtDfUjSr8zW3_ki9oid3xiFNIWG3ubSIjQ-sSchptM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});